### PR TITLE
Add Lambda Spellcrafting Academy.

### PR DESCRIPTION
**Pull request by BitTwiddleGames**
Hi there,

I recently stumbled across your repo. I've made a programming / puzzle game, and would appreciate it if you'd include it in your awesome list of games.

Lambda Spellcrafting Academy (LSA) is a programming game that teaches introductory programming, as well as some data structures and algorithms. The game uses a visual programming language, inspired by Lisp and modeled around arranging a hand of cards.

### CODE REVIEW

**Comment by arcataroger** [comment]
Hi @BitTwiddleGames, and thanks for this PR! Looks like an interesting game you've made :)

So far this list -- which is only a couple days old, btw -- only includes games with Very Positive or higher reviews on Steam. Your game, being newer, doesn't have enough reviews yet :(

However, that could change! Just started a new discussion here... could you please provide any thoughts you might have there? https://github.com/arcataroger/awesome-engineering-games/discussions/15

Let's give it a few days and see what the community thinks?

**Comment by BitTwiddleGames** [comment]
Sounds good, thank you.

**Comment by BitTwiddleGames** [comment]
Thanks for starting the discussion. It sounds like we're open to adding games like this? I've just rebased the change, let me know if you're still interested in merging this one.

**Comment by arcataroger** [comment]
@BitTwiddleGames, I've merged your game (finally!). Thank you again for your patience with this :)

I also highlighted it as the first game in a new section: https://github.com/arcataroger/awesome-engineering-games#newly-released-games

PS Would you like to provide any "Curator's Thoughts" on the game beyond the short description? It can just be a casual sentence or two saying whatever you want to about the game. Totally optional, but might help give it a personal touch.

Thanks again for adding this! I hope to buy a copy with my next paycheck and try it :)

**Comment by BitTwiddleGames** [comment]
Thank you! I've opened https://github.com/arcataroger/awesome-engineering-games/pull/31 with a little comment there.

**Pull request merged**
